"""Template specification (single source of truth).

All constants describing the reading-report / case-report templates live here,
so prompts, orchestrator, compliance checker and renderer share one authority.
"""

from .reading_report_spec import (
    APPENDIX_ORDER,
    CASE_SECTION_ORDER,
    MIN_HIGH_LEVEL_EVIDENCE,
    MIN_REFERENCES,
    MIN_REFERENCES_BY_KIND,
    PAGE_LIMIT_BY_KIND,
    READING_SECTION_ORDER,
    SECTION_WORD_RANGE_CASE,
    SECTION_WORD_RANGE_READING,
    SECTION_WORD_RANGE_TWNA_CASE,
    SECTION_WORD_RANGE_TWNA_PROJECT,
    TOTAL_BODY_CJK_LIMIT_BY_KIND,
    TWNA_CASE_SECTION_ORDER,
    TWNA_PROJECT_SECTION_ORDER,
    ReportKind,
    SectionSpec,
    WordRange,
    min_references_for,
    page_limit_for,
    required_section_names,
    section_names,
    section_order,
    total_body_cjk_limit_for,
    word_range_for,
)

__all__ = [
    "APPENDIX_ORDER",
    "CASE_SECTION_ORDER",
    "MIN_HIGH_LEVEL_EVIDENCE",
    "MIN_REFERENCES",
    "MIN_REFERENCES_BY_KIND",
    "PAGE_LIMIT_BY_KIND",
    "READING_SECTION_ORDER",
    "SECTION_WORD_RANGE_CASE",
    "SECTION_WORD_RANGE_READING",
    "SECTION_WORD_RANGE_TWNA_CASE",
    "SECTION_WORD_RANGE_TWNA_PROJECT",
    "TOTAL_BODY_CJK_LIMIT_BY_KIND",
    "TWNA_CASE_SECTION_ORDER",
    "TWNA_PROJECT_SECTION_ORDER",
    "ReportKind",
    "SectionSpec",
    "WordRange",
    "min_references_for",
    "page_limit_for",
    "required_section_names",
    "section_names",
    "section_order",
    "total_body_cjk_limit_for",
    "word_range_for",
]
